westphalbank/contas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from contas import views
from contas.views import MudaSaldoView

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contas/(?P<conta_id>\d+)$', views.exibir, name='exibir'),
    url(r'^contas/(?P<conta_id>\d+)/convidar$',views.convidar, name='convidar'),
    url(r'^contas/(?P<conta_id>\d+)/sacar$', MudaSaldoView.as_view(), name='sacar'),
    url(r'^contas/(?P<conta_id>\d+)/depositar', MudaSaldoView.as_view(), name='depositar'),
    url(r'^convite/(?P<convite_id>\d+)/aceitar$', views.aceitar, name='aceitar'),
]

westphalbank/usuarios/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from usuarios.views import RegistrarUsuarioView
from usuarios import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^registrar/$', RegistrarUsuarioView.as_view(), name='registrar'),
    url(r'^login/$', auth_views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, {'login_url':'/login/'}, name='logout'),
]

westphalbank/westphalbank/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
#    url(r'^admin/', include('admin.site.urls')),
    url(r'^', include('contas.urls')),
    url(r'^', include('usuarios.urls')),
]

westphalbank/contas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

class Conta(models.Model):
    numero = models.CharField(max_length=255)
    titular = models.CharField(max_length=255, null=False)
    cpf = models.CharField(max_length=11, null=False)
    saldo = models.FloatField(null=False)
    limite = '1000.0'
    contatos = models.ManyToManyField('self')
    usuario = models.OneToOneField(User, related_name="conta")


    def convidar(self, conta_convidado):
        convite = Convite(solicitante=self, convidado=conta_convidado).save()


class Convite(models.Model):
    solicitante = models.ForeignKey(Conta, related_name='convites_feitos')
    convidado = models.ForeignKey(Conta, related_name='convites_recebidos')

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.solicitante.contatos.add(self.convidado)
        self.delete()

def sacar(self, valor):
    self.saldo = self.saldo-valor.save()
    return

def depositar(self, valor):
    self.saldo = self.saldo+valor.save()
    return


class saldo(object):

    numero = models.ForeignKey(Conta, related_name='numero')
    titular = models.ForeignKey(Conta, related_name='titular')
    saldo_conta = models.FloatField(null=False)

    def depositar(self, valor):
        self.saldo_conta = self.saldo_conta + valor
    return

    def sacar(self, valor):
        self.saldo = self.saldo-valor.save()
    return

westphalbank/usuarios/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

westphalbank/contas/forms.py
from django import forms

class MudaSaldoForm(forms.Form):
    valor = forms.FloatField(required=True)


#        def saque(self, valor):
#            self.saldo = self.saldo-valor.save()

#            return render(request, 'conta.html')

#        def depositar(self, valor):
#            self.saldo = self.saldo+valor.save()

#            return render(request, 'conta.html')

westphalbank/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
    numero = forms.DecimalField(required=False)
    titular = forms.CharField(required=True)
    cpf = forms.CharField(required=True)
    saldo = forms.FloatField(required=True)
    senha = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por Favor verifique os dados informados')
            valid = False
        user_exists = User.objects.filter(username=self.data['titular']).exists()

        if user_exists:
            self.adiciona_erro('Usuario ja existente')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

westphalbank/contas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from contas.models import Conta, Convite
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from contas.forms import MudaSaldoForm
from django.views.generic.base import View

@login_required
def index(request):
    return render(request, 'index.html',{'contas': Conta.objects.all(), 'conta_logado': get_conta_logado(request)})

@login_required
def exibir(request, conta_id):
    conta = Conta.objects.get(id=conta_id)
    conta_logado = get_conta_logado(request)
    ja_e_contato = conta in conta_logado.contatos.all()
    return render(request, 'conta.html', {"conta" : conta, 'conta_logado': get_conta_logado(request), 'ja_e_contato': ja_e_contato})

@login_required
def convidar(request, conta_id):
    conta_a_convidar = Conta.objects.get(id=conta_id)
    conta_logado = get_conta_logado(request)
    conta_logado.convidar(conta_a_convidar)
    return redirect('index')

@login_required
def get_conta_logado(request):
    return request.user.conta

@login_required
def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('index')


class MudaSaldoView(View):
    
    template_name = 'sacar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = MudaSaldoForm(request.POST)


    def sacar(request):
        conta_logado = get_conta_logado(request)

        conta_logado.sacar(valor)
        return

    def depositar(request):
        pass

westphalbank/usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from usuarios.forms import RegistrarUsuarioForm
from django.contrib.auth.models import User
from contas.models import Conta

class RegistrarUsuarioView(View):

    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)

        if form.is_valid():
            dados_form = form.data

            usuario = User.objects.create_user(dados_form['titular'], dados_form['cpf'], dados_form['senha'])

            conta = Conta(titular=dados_form['titular'],
                            cpf=dados_form['cpf'],
                            saldo=dados_form['saldo'],
                            usuario=usuario)
            conta.save()
            return redirect('index')

        return render(request, self.template_name, {'form': form })

westphalbank/contas/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Westphal Bank</title>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills float-right">
          <li><a href="{% url 'index' %}">Home </a></li>
          <li><a href="/logout/">Logout</a></li>
        </ul>
        <h3 class="text-muted"> Westphal Bank</h3>
      </div>

      <div class="row content">
        {% block body %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

westphalbank/contas/templates/conta.html
{% extends "base.html" %}
{% block body %}
<div class="row">
  <div class="col-lg-12">
    <h2 style=" margin-top: 0">{{conta.titular}}</h2>

    <address>
      <strong>numero: {{conta.numero}}</strong><br>


      titular: {{conta.titular}},<br>
      cpf: {{conta.cpf}},<br>
      saldo: {{conta.saldo}},<br>
      limite: {{conta.limite}}<br>
    </address>
      <a href="{% url 'sacar' conta.id %}" class="btn btn-success" role="button">Sacar</a>
        <a href="{% url 'depositar' conta.id %}" class="btn btn-success" role="button">depositar</a>
    {% if ja_e_contato %}
      <div class="well well-sm">Vocês estão conectados!</div>
    {% else %}
      <a href="{% url 'convidar' conta.id %}" class="btn btn-success" role="button">convidar</a>
    {% endif %}
  </div>
</div>
{% endblock %}

westphalbank/contas/templates/index.html
{% extends "base.html" %}
{% block body %}
 <div class="col-lg-12">

   <!-- todos os contatos -->
    <div class="card">
      <div class="card-header">
        <strong>Seu Saldo</strong>
      </div>
      
        <p> {{conta.saldo}}
            {{conta.titular}}
        </p>
    </div>

      <!-- lista de todas as contas -->
      <div class="card">
        <div class="card-header">
          <strong>Todos as Contas</strong>
        </div>
      {% if contas %}
      <ul>
        {% for conta in contas %}
          <li>
            <a href="{% url 'exibir' conta.id %}"> {{conta.titular}} /
            {{conta.numero}}</a>
          </li>
          {% endfor %}
        </ul>
        {% else %}
        <p>Nenhuma Conta encontrada</p>
        {% endif %}

    <!-- Convites pendentes-->
    <div class="card">
      {% with total_de_convites=conta_logado.convites_recebidos.count %}
         <div class="card-header">
             <strong>Voce tem {{ total_de_convites }} convite{{ total_de_convites|pluralize }} aguardando aprovação</strong>
         </div>
         <ul class="list-group">
           {% if total_de_convites %}
            {% for convite in conta_logado.convites_recebidos.all %}
              <li class="list-group-item">
                  {{ convite.solicitante.titular }}
                <a href="{% url 'aceitar' convite.id %}" class="float-right">aceitar</a>
              </li>
            {% endfor %}
            {% else %}
              <div class="card-body">
                <p>Nenhum convite recebido :(</p>
              </div>
            {% endif %}
         </ul>
      {% endwith %}
    </div>

    <!-- Contatos aceitos-->
    <div class="card">
      {% with total_de_contatos=conta_logado.contatos.count %}
      <div class="card-header">
        <strong>Todos os seus contatos</strong>
      </div>
      <ul class="list-group">
        {% if total_de_contatos %}
          {% for contato in conta_logado.contatos.all %}
            <a href="{% url 'exibir' contato.id %}" class="list-group-item">{{contato.titular}} // {{contato.numero}}</a>
          {% endfor %}
        {% else %}
        <div class="card-body">
          <p>Nenhum contato encontrado</p>
        </div>
        {% endif %}
      </ul>
      {% endwith %}
    </div>



  </div>
  {% endblock %}

westphalbank/contas/templates/sacar.html
{% extends "base.html" %}
{% block body %}
  <form class="form-group" action="{% url 'sacar' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading"><strong>Saque</strong></h2>

    <input id="id_sacar" type="text" name="sacar"
      class="form-control" placeholder="Valor a sacar"
      required>
    <hr/>

    <button class="btn btn-lg btn-primary btn-block" type="submit" name="button">Sacar</button>
    <hr/>
  </form>

{% endblock %}

westphalbank/usuarios/templates/base_usuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta name="viewport" content="width=device-width" charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Westphal Bank</title>
  </head>
  <body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
  </body>
</html>

westphalbank/usuarios/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

  <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
      {% csrf_token %}

      <h2 class="form-signin-heading">Login</h2>

      <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>

      <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

      <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

      <input type="hidden" name="next" value="{{ next }}" />

      {% if form.errors %}
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          Por favor, verifique o Usuario e/ou Senha informados
        </div>
      {% endif %}

      <a href="{% url 'registrar' %}">registre-se</a>
  </form>

{% endblock %}

westphalbank/usuarios/templates/registrar.html
{% extends "base_usuario.html" %}
{% block body %}
  <form class="form-group" action="{% url 'registrar' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading"> Crie sua conta no Westphal Bank</h2>

    <input id="id_numero" type="text" name="numero"
      class="form-control" placeholder="numero da conta *">
    <hr/>

    <input id="id_titular" type="text" name="titular"
      class="form-control" placeholder="titular *"
      required>

    <hr/>

    <input id="id_cpf" type="text" name="cpf"
      class="form-control" placeholder="cpf *"
      required>

    <hr/>

    <input id="id_saldo" type="text" name="saldo"
      class="form-control" placeholder="saldo inicial *"
      required>

    <hr/>

    <input id="id_senha" type="password" name="senha"
      class="form-control" placeholder="senha *"
      required>

    <hr/>

    <button class="btn btn-lg btn-primary btn-block" type="submit" name="button">Registrar</button>
    <hr/>

    {% if form.errors %}
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true" >&times; </button>
        {{form.non_field_errors}}
      </div>
    {% endif %}


  </form>

{% endblock %}